apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-robot-shop-phwj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-robot-shop-phwj
    app.kubernetes.io/part-of: my-app
  name: mongo-robot-shop-phwj
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: mongo-robot-shop-phwj
status:
  loadBalancer: {}
