apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: load-gen-robot-shop-iisa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: load-gen-robot-shop-iisa
    app.kubernetes.io/part-of: my-app
  name: load-gen-robot-shop-iisa
  namespace: srevivo-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: load-gen-robot-shop-iisa
    weight: 100
status: {}
