apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: load-gen-robot-shop-iisa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: load-gen-robot-shop-iisa
    app.kubernetes.io/part-of: my-app
  name: load-gen-robot-shop-iisa
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: load-gen-robot-shop-iisa
status:
  loadBalancer: {}
