apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalogue-robot-shop-mke1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalogue-robot-shop-mke1
    app.kubernetes.io/part-of: my-app
  name: catalogue-robot-shop-mke1
  namespace: srevivo-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: catalogue-robot-shop-mke1
    weight: 100
status: {}
