apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalogue-robot-shop-mke1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalogue-robot-shop-mke1
    app.kubernetes.io/part-of: my-app
  name: catalogue-robot-shop-mke1
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: catalogue-robot-shop-mke1
status:
  loadBalancer: {}
