apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fluentd-robot-shop-ur23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fluentd-robot-shop-ur23
    app.kubernetes.io/part-of: my-app
  name: fluentd-robot-shop-ur23
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: fluentd-robot-shop-ur23
status:
  loadBalancer: {}
