apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dispatch-robot-shop-ye1g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dispatch-robot-shop-ye1g
    app.kubernetes.io/part-of: my-app
  name: dispatch-robot-shop-ye1g
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: dispatch-robot-shop-ye1g
status:
  loadBalancer: {}
