apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipping-robot-shop-f3q0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipping-robot-shop-f3q0
    app.kubernetes.io/part-of: my-app
  name: shipping-robot-shop-f3q0
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: shipping-robot-shop-f3q0
status:
  loadBalancer: {}
