apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cart-robot-shop-d6ph
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cart-robot-shop-d6ph
    app.kubernetes.io/part-of: my-app
  name: cart-robot-shop-d6ph
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: cart-robot-shop-d6ph
status:
  loadBalancer: {}
